server:
  port: 8001

logging:
   level:
      root: WARN
      org:
         springframework:
            web: INFO
      '[com.bylvin]': INFO

app:
   http:
      connect-timeout: 5000
      read-timeout: 5000
   telegram:
      bot:
         username: "@cdsdev04_bot"
         token: NzY3Mzc3NDk3NzpBQUU4TlhoR2FIMEFuVDk0LXREc0x5eWo5Y3Z1c0MwTWhxYw==

spring:
   ai:
      ollama:
         chat:
            model: llama3.1
   datasource:
      hikari:
         jdbc-url: jdbc:postgresql://localhost:5432/langlearn_bot
         driver-class-name: org.postgresql.Driver
         username: user1
         password: cH4t13OTD3v!#
         connection-timeout: 5000
         minimum-idle: 5
         maximum-pool-size: 20
         idle-timeout: 200000
         max-lifetime: 1000000
         auto-commit: true